### ISSUE TITLE
Translation only translates first sentence

### ISSUE THREAD

**Issue by ejjjjkang** [botbahlul/crx-live-translate#3]
Hi, Thank you for the tool!
It seems that the translation only works at the beginning, which means that when speaker said it first translates well but stop after 10 secs. I tested it at Eng - Kor.
Is it also related to CORS ?

**Comment by botbahlul** [comment]
I'm not sure what's the problem. It's happened to me too with ENGLISH VOICE. Mostly I have to turn it OFF and ON again when the sentence finished. Other languages voice run fine.
It seems that WEBKITSPEECHRECOGNITION has problems with English voice (or maybe they're just limiting it to listen for one sentence only because it's free API?).
You can try my other apps like https://github.com/botbahlul/pyvosklivesubtitle or else (see my repo page).

**Comment by botbahlul** [comment]
> Hi, Thank you for the tool! It seems that the translation only works at the beginning, which means that when speaker said it first translates well but stop after 10 secs. I tested it at Eng - Kor. Is it also related to CORS ?

I think I've found the problem. It looks like that the problem came from the streaming site. Their own javascript seems sometimes blocks this extension.
There's nothing we can do about it, because it's their site, their rules :(
If you watch on a streaming site that has no blocking javascript, this extension will run fine on any languages.
